### ISSUE TITLE
discover npm account management package 

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#102]
We have a lot of problems which could be solved by using an npm account management package.
we should explore and implement account management module to extend krl functionality.

**Comment by burdettadam** [comment]
lets use https://www.npmjs.com/package/bcrypt for password hashes.

**Comment by 0joshuaolson1** [comment]
This looks like it adds a build step/native dependency. @farskipper are you okay with this one?

**Comment by farskipper** [comment]
Yeah I'd prefer we stay away from adding native dependencies. But I guess bcrypt is probably the recommended way of hashing passwords.

There is a pure js version with no native dependencies [bcryptjs](https://www.npmjs.com/package/bcryptjs) that is only ~30% slower than C.

So similar to `leveldown`, we can use the faster native `bcrypt` package by default. But on a system with build issues it can fall back to a slower `jsondown` and `bcryptjs`.

Another option is just using sha2 hashes with salts using node's built-in `"crypto"`.

**Comment by burdettadam** [comment]
I believe the problem of hashing passwords has been solved. closing.
