### ISSUE TITLE
unique pico name

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#103]
wrangler currently only checks a single descendants for name uniqueness. This allows a grand child to have the same name as grand parent.  
To enforce a owner scoped unique name we could store the parent child tree structure as an app variable keyed to the owner pico_id. App variable would allow tree traversal in each child to be done without using sky query. This would make checking names very quick and easy.  
By using the owner pico_id as the key to this structure, other owners using wrangler would still have to do difficult fishing to discover other pico_ids.

**Comment by windley** [comment]
Let's distinguish between names and IDs. Are we talking about the pico ID or a name (i.e. human readable/memorable string)? I think we might want different things for these.

**Comment by burdettadam** [comment]
wrangler stores a human readable name. The engine uses pico ID to identify picos. 
wrangler has been developed towards the goal that a user could us the human readable name as the pico_ID. Currently uniqueness is only guaranteed for one generation. Im proposing storing a direct mapping of human readable names to pico_ids in an app variable structured by the "family Tree".

How should it be? Should wrangler store unique human readable names?

**Comment by LewisThomas** [comment]
I'm going forward with this under the assumption a pico's "name" does not have to be unique for owner scope. IDs already ensure lack of inter-pico conflicts for engine scope and channels for global scope. Making wrangler name's unique at owner scope does not make sense to me from a design perspective or use case perspective (imagine multiple "Smart Lights" or "Door"s). I think wrangler's name can even be seen as a loose type for a pico.

If anyone has a problem with this let me know.

**Comment by windley** [comment]
I think this is fine.

**Comment by LewisThomas** [comment]
Done.
https://github.com/Picolab/pico-engine/pull/456

**Comment by windley** [comment]
Thanks Thomas.
