### ISSUE TITLE
randomPicoName

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#110]
randomPicoName should be updated to use the updated random name function from subscriptions. Currently it does not "guarantee" a random name.

**Comment by LewisThomas** [comment]
I believe it does guarantee a random name now but the function needs improvement anyway. I also don't see a random name function in subscriptions.

**Comment by LewisThomas** [comment]
Now after 200 guaranteed to be random names pico children names will be a UUID. https://github.com/Picolab/pico-engine/pull/456

**Comment by windley** [comment]
Good plan.
