### ISSUE TITLE
provide/share createChannel

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#111]
wrangler does not currently share or provide createChannel. Is this a security feature or incomplete module API.

**Comment by windley** [comment]
I can’t, off the top of my head, think of a reason that we wouldn’t want to allow rulesets to create channels.

**Comment by cgrimm013** [comment]
We added the createChannel defaction to the provides pragma, and also created a newPolicy defaction and provided it as well.

**Comment by LewisThomas** [comment]
Done https://github.com/Picolab/pico-engine/pull/456
