### ISSUE TITLE
Friendly wrangler:skyQuery

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/wrangler#117]
Right now, wrangler's skyQuery is pretty gross. It takes 7 parameters that you have to delve deep to understand what it is supposed to be doing. It is not friendly to use and I recommend cutting it down to focus on http cleanup. We can remove most of the parameters and just have an options parameter that is a map and contains any of the other optional information we might want to work with.

**Comment by LewisThomas** [comment]
SkyQuery is a lot friendlier now, but I also suggest on top of this issue a modification to SkyQuery so that a Pico cannot query itself.

**Comment by windley** [comment]
Or just short circuit it. I.e. don't fail if you can do the right thing.

**Comment by LewisThomas** [comment]
I changed my mind, a pico should not have to loop through every single one of its channels every time it wants to make a skyQuery request, and channels are given by the engine module as an array. 

@cgrimm013 what do you mean by focusing on http cleanup? Which parameters would you remove from the function? Maybe we could remove the _path and _root_url params and just keep the _host param. Or would you prefer to remove all three and replace them with a map

**Comment by windley** [comment]
This is skyQuery in KRL, not the JS, right? 

Could Wrangler create a map from the array and update is on a newChannel event (I'm presuming there's one)?

**Comment by LewisThomas** [comment]
Yes this is the KRL skyQuery. I didn't know we had a JS skyQuery, the KRL skyQuery uses KRL's http:get function. Wrangler could maintain a separate map of channels the pico knows about, but it would add significant complexity to the code for O(1) access time. This is similar to Wrangler keeping track of children separately, even though the engine is truly responsible.

**Comment by LewisThomas** [comment]
skyQuery now fails if a pico trys to query itself.
https://github.com/Picolab/pico-engine/pull/456
