### ISSUE TITLE
Make eci optional in createChannel()

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#12]

**Comment by burdettadam** [comment]
I think this is done, but untested.

**Comment by burdettadam** [comment]
Done; 
configure using eci = meta:eci();

no easy way to test if you can pass a different eci with out creating new rules.

**Comment by windley** [comment]
Please add rules for testing configuration too.

**Comment by burdettadam** [comment]
I think a simpler solution would be to put a defaults To Meta:eci when accessing event:attribute, this would eliminate an entire rule.

**Comment by windley** [comment]
You're speaking of how to test this?

**Comment by burdettadam** [comment]
Using "configure using" inside create channel defaction to allow an optional eci passed in is a good idea and creates a better system. I think a more elegant solution to allow an optional eci to be passed in would be to place a defaultsTo(meta:eci,"") in the rules pre-block. This would allow a user to pass a desired eci but have the system use meta:eci if one was not provided.
Should Create channel allow you to create channels inside other picos? Allowing users to pass in an eci of a pico to create a channel inside of could create some security issues (injected subscriptions). If we forced events to be passed into a pico to create a channel, future policy could regulate those events.
This is implemented and tested.
