### ISSUE TITLE
Custom attrs in subscriptions

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/wrangler#122]
Currently, wrangler subscriptions does not allow you to tag on extra custom attributes. What if I want to provide a name and location in the subscription itself? Should we allow for this? Lab7 of the CS462 class currently has you keeping track of all of the sensor picos and asks you to migrate over to using subscriptions, but when checking if a pico name already exists, how are they supposed to use subscriptions, if all it contains is a role and eci?

**Comment by burdettadam** [comment]
I propose we add an entity variable for extending subsctriptions. I do not think we should add an extra layer to the returned structure. Instead we could append subscription key:value to this entity variable. That way any collisions will favor subscription structure, preserving current functionality.

**Comment by burdettadam** [comment]
I now propose we add every event attribute, key:value, passed to the subscription event as a structure.

**Comment by burdettadam** [comment]
subscriptions now have a correlation id that can be used to easily track subscriptions.  Also any extra attributes raised with a subscription event is chained along with all events so you can also use that as a correlator. But there are no regression test for that feature so it is not guaranteed. closing.
