### ISSUE TITLE
subscriptions auto-accept management 

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#123]
There is no way to remove or update an auto-accept configuration. There should be.

**Comment by LewisThomas** [comment]
When a configuration is changed should it go through inbound subscriptions and accept them if they match the auto accept schema?

**Comment by LewisThomas** [comment]
I just realized with current subscriptions this is not possible as auto-accept looks for event attributes passed along through wrangler:inbound_pending_subscription_added, and those attributes are not saved in ent:inbound

Also, can now update/delete/add auto-accept configurations through new API.

**Comment by LewisThomas** [comment]
There is now, althought auto-accept may be phased out eventually.
