### ISSUE TITLE
Deleting Pico does not remove scheduled events for the pico

### ISSUE THREAD

**Issue by BTBingham** [Picolab/wrangler#137]
When you have a Pico with recurring events on the scheduler (say every 5 seconds) and delete that pico the corresponding scheduled events are not also deleted

**Comment by LewisThomas** [comment]
I believe this should go in the pico-engine repo. As I understand it scheduled events are handled by the engine, not wrangler.

**Comment by LewisThomas** [comment]
I created an issue there
