### ISSUE TITLE
Attributes for wrangler:inbound_pending_subscription_added aren't complete

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#14]
Here are the attributes that are passed:

```
{"status":"inbound",
 "channel_name":"esproto-meta:impervious",
 "name":"Collection-Device"
}
```

We ought to be passing `name_space` and `relationship` as well

**Comment by burdettadam** [comment]
inbound_pending_subscription_added now includes name_space, relationship, my_role, target_role, attributes and channel_type.

**Comment by windley** [comment]
Let's rename `target_role` to `subscriber_role`

**Comment by windley** [comment]
Rename back channel and target channel too as "inbound" and "outbound". @burdettadam
