### ISSUE TITLE
Child pico changes order in list

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#15]
The ordering in this list changes from refresh to refresh. Let's sort by name

![screenshot 2016-04-22 11 19 12](https://cloud.githubusercontent.com/assets/275079/14749325/1b63d990-087c-11e6-805f-cf4ea3fcef6b.png)

**Comment by earlyprogrammer** [comment]
now sorting by name

**Comment by windley** [comment]
Yeah!
