### ISSUE TITLE
Auto subscribe ruleset

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#16]
Create autosubscribe ruleset that can be selectively installed in a pico (i.e. via the prototype)

There should be a rule for configuring the auto subscribe (limiting it to parent, specific inbound channels, etc. )

**Comment by burdettadam** [comment]
The ruleset currently written allows you to dynamically give a list of properties to look for on a inbound request, no complex pattern recognition.

**Comment by windley** [comment]
let's try to also use channel attributes

**Comment by windley** [comment]
Add equality checking for attributes.

**Comment by cgrimm013** [comment]
This issue will be addressed in the subscription ruleset rewrite. #99
