### ISSUE TITLE
javascript testing 

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#18]
we need to create an account for testing. javascript test driver will use wrangler.js  to create a child pico in the testing account and test functionality in the child.

**Comment by burdettadam** [comment]
![uploads/7277f166-99cf-41fc-b5c3-660b412db13e/Screen Shot 2016-05-06 at 5.37.33 PM.png](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F7277f166-99cf-41fc-b5c3-660b412db13e%2FScreen+Shot+2016-05-06+at+5.37.33+PM.png)
test driver so far.

**Comment by windley** [comment]
Looks good. Let’s talk Monday about next steps.

**Comment by cgrimm013** [comment]
Closing. This issue may come up again, but will likely be modeled after how the NPE runs its tests. We will make a new issue when we feel closer to this area.
