### ISSUE TITLE
Refactor createChildFromPrototype

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#19]
1. Not `core`, but `base`
2. Change definition/name as shown below
3. Let prototype defn have meta, rids, events, channels
4. Send prototype to child and store in ent var so child knows what kind of thing it is and can raise events and create channels. 

Defaction: 

```
createChild = defaction(name) {
  configure using prototype_name = "base"
  ...
}
```

Use: 

```
if ... then
   createChile ("flipper") with prototype_name = "esproto_msa_01"
```

**Comment by windley** [comment]
Test this @burdettadam

**Comment by burdettadam** [comment]
https://github.com/Picolab/wrangler/pull/79/commits/d5c3d963f83da8cf6a410149226defe4857e4a57
the spelling of prototype will be corrected in the next pull I make with wrangler.
This code produces new pico chidden of desired prototype. TedTested.
