### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#2]

**Comment by burdettadam** [comment]
I suggest that we use Doxygen to generate documentation from wrangler.js. Doxygen(and others) will not parse KRL correctly and extract comments to generate documentation, if we place all documentation in wrangler.js we will be able to generate docs as we planned. In the future we could update KRL parser to retain comments in the parsed tree and use that to create a plug in for Doxygen. 
Doxygen will generate docs in Latex that we can then use to format how we would like for confluence documentation website.

**Comment by windley** [comment]
Agree. Doxygen looks good. 

Let's (@burdettadam & @AngellNick) explore how much work a Doxygen parser for KRL would take. Are we talking "Sublime integration" level of effort or something much bigger than that?  Doesn't it just extract comments that match a certain pattern and use them? I suspect it knows nothing about events. 

Also, there's a [Doxygen in Confluence](https://www.appfusions.com/display/DOXYGEN/Home) plugin apparently.  @eisbaerBorealis could you explore that and let me know what your think?

**Comment by windley** [comment]
Decided to not use Doxygen.

**Comment by burdettadam** [comment]
closing. we will be documenting on the documentation page.
