### ISSUE TITLE
Relationship reported by subscriptions() isn't a relationship

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#22]
We're asking for "my role" and "your role" (which out to be "my role" and "target's role") but the relationship field returned by subscriptions() is just "your role". A relationship needs at least two sides.

**Comment by burdettadam** [comment]
subscriptions will now store my_role and target_role with relationship stored as my_role+"<->"+target_role, looking like Father<->Son.

**Comment by windley** [comment]
Why combine them in a single field instead of putting them in two different fields:
- my role
- subscriber role
  With a combined field the programmer has to remember the order (which is my role, the first or second) and take then apart each time.

**Comment by burdettadam** [comment]
I store all three. my_role, target_role and a relationship that represents them both.

**Comment by windley** [comment]
OK, good.
