### ISSUE TITLE
Allow subscriptions request to be made with prototypes. 

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#23]
Prototypes should include subscription request creation.

**Comment by windley** [comment]
See my suggestion at the bottom of my last blog post on [picos and ESProto](http://www.windley.com/archives/2016/05/a_pico-based_platform_for_esproto_sensors.shtml)

Specifically, the style of the prototype specification and the use of optional parameters for `new_child()`

If `new_child()` is called without any of the optional parameters if creates a child with a generated name (the dictionary combination thing is good) and with the default prototype.

**Comment by burdettadam** [comment]
Prototypes now include subscription requests at creation. see https://github.com/Picolab/wrangler/blob/master/rulesets/wrangler.krl#L440  (request structure),
https://github.com/Picolab/wrangler/blob/master/rulesets/wrangler.krl#L1096 (base init) and
https://github.com/Picolab/wrangler/blob/master/rulesets/wrangler.krl#L1206 (prototype init).
Also Dr. Windley's comment has been posted on issue #40 for improvements on pico names.
