### ISSUE TITLE
wrangler.raiseEvent _path, _host param

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#26]
wrangler.raiseEvent needs to be updated to take a _host and _path param.

**Comment by windley** [comment]
And _port

**Comment by windley** [comment]
Instead, we could use `_apiRoot`

   ..._apiRoot="https://pe.windley.com:4331/v1/sky/events/

**Comment by burdettadam** [comment]
instead of host, path, and port, we should use apiRoot?

**Comment by burdettadam** [comment]
check out pull request #67 https://github.com/Picolab/wrangler/pull/67 . adds _host, _path and _apiRoot. not fully tested.

**Comment by windley** [comment]
So, we either use _host and _path or just _apiRoot?
