### ISSUE TITLE
test installing multiple rulesets from array. 

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#28]
how can we test multiple ruleset installs from an array with our current test driver that uses post/get request? normally a user would encode array before sending, we do not decode the incoming list, so only internal function calls would pass arrays in..

**Comment by burdettadam** [comment]
I propose we create a ruleset for testing some things that are difficult to test with java. this would allow some duplicate code to be removed from wrangler. We could also simplify the java script tester by adding some check functions in the test ruleset.

**Comment by windley** [comment]
Good idea.

**Comment by cgrimm013** [comment]
Now irrelevant. Testing will be implemented differently when we need to do so.
