### ISSUE TITLE
Find way to pull documentation from source code for wiki

### ISSUE THREAD

**Issue by eisbaerBorealis** [Picolab/wrangler#35]
At the moment Adam and I are looking at using Doxygen and LaTeX

**Comment by windley** [comment]
Cool. I know LaTex well, or at least I did.

**Comment by burdettadam** [comment]
we decided to just put documentation on the documentation web site(https://picolabs.atlassian.net/wiki/).

**Comment by windley** [comment]
Good choice for now.
