### ISSUE TITLE
auto generate child pico names 

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#40]
If new_child() is called without any of the optional parameters it creates a child with a generated name (the dictionary combination thing is good) and with the default prototype.

**Comment by burdettadam** [comment]
should unique names for child picos be enforced? We currently only use picos eci to interact so I see no need to enforce unique names.

**Comment by windley** [comment]
I believe we should entice unique names for child picos. We want to be able to reliably refer to them by name (or what’s the point of the name).

**Comment by burdettadam** [comment]
first auto generated name is 1?

**Comment by burdettadam** [comment]
Comment from Dr. Windley on issue #23 (which is closing).

See my suggestion at the bottom of my last blog post on [picos and ESProto](http://www.windley.com/archives/2016/05/a_pico-based_platform_for_esproto_sensors.shtml)

Specifically, the style of the prototype specification and the use of optional parameters for `new_child()`

If `new_child()` is called without any of the optional parameters if creates a child with a generated name (the dictionary combination thing is good) and with the default prototype.

**Comment by burdettadam** [comment]
random pico name used checkPicoName, so this pull https://github.com/Picolab/wrangler/pull/91corrected this issue. I also have not been able to recreate name being 1. 1 being generated as a name must be a strange edge case that is a different issue. Im closing this one.
