### ISSUE TITLE
Using channel name in subcriptions

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#42]
After creating a subscription (using Devtools), and then listing subscriptions with wrangler, I see this:

```
"subscriptions": [1]
    0:  {
        "Closet:mosquito": {
            "name_space": "Closet"
            "relationship": "Thermostat<->Temperature Sensor"
            "status": "subscribed"
            "channel_name": "Closet:mosquito"
            "inbound_eci": "0A053108-4F99-11E6-A902-F9F0E71C24E1"
            "subscriber_role": "Temperature Sensor"
            "my_role": "Thermostat"
            "subscriber_eci": "C6ADDC50-485B-11E6-9AAC-42DDE71C24E1"
            "subscription_name": "Temperature"
            "attributes": "status"
            "outbound_eci": "0AF50B24-4F99-11E6-98E8-D4E9E71C24E1"
        }
}
```

Note that "mosquito" is the name of the channel. I didn't enter it. It was generated for me. Generating the name is good, but then using that generated name as a key for accessing stuff isn't. 

Channels in subscriptions should _not_ be elevated to the primary thing. The subscription is the thing. So why isn't the key for this "Closet:Temperature", using the namespace and subscription name?   

Why is this an array of what appear to be single-value hashes? 

This should probably be a two-tier hierarchy:

```
{"Closet" : {"Temperature": {...}
                    ...
                  }
}
```

Right? Combining values to make keys is generally poor design since the user has to know both and how they're combined to get a value.  For example, the current structure makes it _very_ hard to return the subscriptions in a specific namespace. 

And why is "status" an attribute?  Attributes should be key-value pairs. 

@b1conrad @eisbaerBorealis

**Comment by burdettadam** [comment]
I agree we can make this a lot better. 
so a subscription should be an object with the name of the subscription as the key?
subscriptions should return a collection of subscriptions by name_space? 
if a user creates a duplicate subscription with same name and name_space it should fail?
the channel created for the subscription should have a random name generated or should we allow an entry like we do with channel type?

status as a key-value pair? What you do you mean by "key-value Pair"?
status is an attribute used in the subscription rulesets as a logic switch. Currently the same rule in each pico will behave differently dependent on what the status of the subscription is. its used to identify a subscriptions state. 
currently if you wanted to return subscriptions collection by namespace you would call, wrangler:subscriptions(unknown,"name_space",unknown);  
currently if you wanted to return subscription collection by namespace with name_space equal to Closet you would call,
wrangler:subscriptions(unknown,"name_space","Closet");
or a simpler call to get a particular subscription would be,
wrangler:subscriptions("Closet:mosquito",unknown,unknown);
also you could use the subscription name like this,
wrangler:subscriptions("Temperature",unknown,unknown);
or 
wrangler:subscriptions(unknown, "subscription_name","Temperature");
How should it behave in our next version?

**Comment by burdettadam** [comment]
subscriptions are now keyed and "subscription_name":{"subscription"..}.
the channel name is now "subscription_namespace"+":"+"subscription_name". 
subscription without a name provided will receive a random generated name. a duplicated subscription name and name space will result in failed attempt with logs. 
this is still under testing and open for change.
