### ISSUE TITLE
channel returns channels with cid as a keyed attribute not eci.

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#43]
while pci still returns cids we should reconstruct channels to have ecis instead. we have moved away from calling event channel identifiers "cid".

**Comment by windley** [comment]
Agree

**Comment by windley** [comment]
When you close something like this, it's helpful if you put the commit ID in the comment so others can click thru and see the code. @burdettadam

**Comment by burdettadam** [comment]
commit ID 91ed760cbfe747b9649de91e3e5d8e1c1fce4899

**Comment by windley** [comment]
Thanks. That looks good.
