### ISSUE TITLE
Change skyQuery() to allow _host param to set host. 

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#5]
Defaults to meta:host()

**Comment by burdettadam** [comment]
wrangle.js skyQuery also needs a _path param.
the params will be passed in with the options structure and default to definitions provided in wrangler-config.js

**Comment by burdettadam** [comment]
skyquery in wrangler.krl needs the same.

**Comment by windley** [comment]
And _port

**Comment by windley** [comment]
We could just have a _rootUrl param and let people write the whole thing:

```
https://pe.windley.com:4331/sky/event
```

That would be simpler

**Comment by burdettadam** [comment]
https://github.com/Picolab/wrangler/pull/69
