### ISSUE TITLE
Combine channel() and channels()

### ISSUE THREAD

**Issue by windley** [Picolab/wrangler#8]

**Comment by windley** [comment]
Also refactor to return standard error information so it can be public

If identifier given (use id for argument name) then returns single channel, otherwise returns array

**Comment by burdettadam** [comment]
solved with the help of wranglers test driver.

**Comment by windley** [comment]
Good!

On Fri, May 13, 2016 at 3:59 PM -0700, "Adam Burdett" notifications@github.com wrote:

solved with the help of wranglers test driver.
