### ISSUE TITLE
incoming subscription duplicate 

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#83]
subscription management does not check if an incoming subscription is a duplicate. This will allow someone to accept a duplicate subscription which could lead to undesired pico system behavior. subscription management should check if a incoming subscription is a duplicate and automatically reject it, and raise a duplicate subscription event back to the subscription requestor.

**Comment by windley** [comment]
It should be possible to have more than one subscription between two picos with different names, but not with the same names. I might have two picos that have two applications that use two of my picos in different ways, for example. One a subscription has a policy attached to it, I need different subscriptions for different purposes.

**Comment by cgrimm013** [comment]
We will address this issue in the subscription rewrite. Closing until then.
