### ISSUE TITLE
subscription query testing

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#86]
when we changed subscriptions to be a object with subscription name as the key. we over looked updating the regular expression used to identifie whether eci or subscription is used to get a single subscription. this needs to be tested and updated. the current code uses a split that may only affect special cases. This split may simply need to be removed.

**Comment by burdettadam** [comment]
checkSubscriptionName needs the structure of the channel name checked with what subscriptions has been updated to as well

**Comment by cgrimm013** [comment]
This issue will be addressed as we rewrite subscriptions. #99
