### ISSUE TITLE
subscriptions ruleset rewrite

### ISSUE THREAD

**Issue by burdettadam** [Picolab/wrangler#99]
Subscriptions could benefit from a different persistence structure. There is a fork which started to simplify the event api that should be used for this issue.

**Comment by burdettadam** [comment]
we need to document subscription getter function. #20

**Comment by burdettadam** [comment]
we need to test and document subscriptions to other KRE's.

**Comment by 0joshuaolson1** [comment]
it works with other Node pico engines.

**Comment by burdettadam** [comment]
Ruleset has been rewritten and is undergoing user testing.  I am closing this issue. Any new bugs / features will be new issues.
